# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(760, 474)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon/donga.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(parent=mainWindow)
        self.label_2.setGeometry(QtCore.QRect(250, 90, 461, 351))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/nguye/OneDrive/Hình ảnh/TOTO-100-scaled.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(parent=mainWindow)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 761, 81))
        self.groupBox.setStyleSheet("background-color: rgba(0, 119, 182,1)\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(110, 20, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.sach_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.sach_pushButton.setGeometry(QtCore.QRect(30, 405, 171, 23))
        self.sach_pushButton.setObjectName("sach_pushButton")
        self.viPham_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.viPham_pushButton.setGeometry(QtCore.QRect(30, 307, 171, 23))
        self.viPham_pushButton.setObjectName("viPham_pushButton")
        self.tacGia_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.tacGia_pushButton.setGeometry(QtCore.QRect(30, 209, 171, 23))
        self.tacGia_pushButton.setObjectName("tacGia_pushButton")
        self.theLoai_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.theLoai_pushButton.setGeometry(QtCore.QRect(30, 356, 171, 23))
        self.theLoai_pushButton.setObjectName("theLoai_pushButton")
        self.muonTra_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.muonTra_pushButton.setGeometry(QtCore.QRect(30, 111, 171, 23))
        self.muonTra_pushButton.setObjectName("muonTra_pushButton")
        self.admin_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.admin_pushButton.setGeometry(QtCore.QRect(30, 258, 171, 23))
        self.admin_pushButton.setObjectName("admin_pushButton")
        self.banDoc_pushButton = QtWidgets.QPushButton(parent=mainWindow)
        self.banDoc_pushButton.setGeometry(QtCore.QRect(30, 160, 171, 23))
        self.banDoc_pushButton.setObjectName("banDoc_pushButton")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Trang chủ"))
        self.label.setText(_translate("mainWindow", "QUẢN LÝ THƯ VIỆN TRƯỜNG ĐẠI HỌC"))
        self.sach_pushButton.setText(_translate("mainWindow", "Quản lý sách"))
        self.viPham_pushButton.setText(_translate("mainWindow", "Quản lý vi phạm"))
        self.tacGia_pushButton.setText(_translate("mainWindow", "Quản lý tác giả"))
        self.theLoai_pushButton.setText(_translate("mainWindow", "Quản lý thể loại"))
        self.muonTra_pushButton.setText(_translate("mainWindow", "Lịch sử mượn trả"))
        self.admin_pushButton.setText(_translate("mainWindow", "Quản lý Admin"))
        self.banDoc_pushButton.setText(_translate("mainWindow", "Quản lý bạn đọc"))
